### ISSUE TITLE
Write Research Plan

### ISSUE THREAD

**Issue by Globnartheexquisite** [saucelabs/elemental-bromine#10]
# Description

We need to create a plan for our design research in order to ensure good research. 

# Acceptance Criteria

- [x] A document which contains the final form of our research plan.

**Comment by aquaomarine** [comment]
[Research Plan](https://docs.google.com/document/d/1JBKIhb-roQEedD9EiVJViWZLTpi9ZNUaCFT-xr8wnCg/edit#heading=h.wtt4ns4mtk4z)

**Comment by Roseywinter** [comment]
Research Plan completed; closing issue.
