### ISSUE TITLE
Write Interview Questions

### ISSUE THREAD

**Issue by Globnartheexquisite** [saucelabs/elemental-bromine#11]
# Description

Based on the research plan, we will write questions for our user interviews. 

# Acceptance Criteria 

- [x] 1st draft of interview questions to be approved by Sauce Labs's User Research Department 
- [x] Questions reviewed by UxRD

**Comment by aquaomarine** [comment]
[User Interview Questions](https://docs.google.com/document/d/1JBKIhb-roQEedD9EiVJViWZLTpi9ZNUaCFT-xr8wnCg/edit#heading=h.wtt4ns4mtk4z) Has been approved by Sauce Labs UxRD

**Comment by Roseywinter** [comment]
Interview Questions written and approved by UxRD; issue closed.
