### ISSUE TITLE
Select interview candidates

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-bromine#14]
# Description

Select 5-8 interview candidates from the survey responses who were interested. 

# Acceptance criteria

- [x] 5-8 candidates selected
- [x] Emails send out to candidates

**Comment by aquaomarine** [comment]
Reviewed [Doc](https://docs.google.com/spreadsheets/d/1SoFU40uctzZbQPc92ONQpIiQvxfI4YZDbBIvpx50IEU/edit?resourcekey&skip_itp2_check=true#gid=169596544)
