### ISSUE TITLE
Calendly Template

### ISSUE THREAD

**Issue by aquaomarine** [saucelabs/elemental-bromine#24]
#Description

Create a short intro thanking users for their participation in the surveys, and setting aside time  for a short call.

##Context

This template will explain what will be discussed during the call and how this information will be used to help improved Elemental Selenium.

**Comment by discombobulateme** [comment]
@aquaomarine, I am putting this issue back in review instead of done as we do not have access to it.
Could you please share a link to the document and attribute a reviewer to it?

Thank you :)

**Comment by aquaomarine** [comment]
Team Element reviewed during a call, together with mentor Marija, on January 26
[document link](https://docs.google.com/document/d/1lZs5P9p-bisvdM9aI4A5sdMiqjjqJ_cggCmeT0XJ6mg/edit#heading=h.y7sq2d4wkre7)
