### ISSUE TITLE
Set Up Calendly

### ISSUE THREAD

**Issue by aquaomarine** [saucelabs/elemental-bromine#25]
# Description

Set up Calendly for easier allocation of interview slots using the Calendly template.

## Context 

Calendly helps allocate user interview slots, and help inform the candidates on how their contribution will bused for Elemental Bromine

**Comment by discombobulateme** [comment]
@aquaomarine could you please share where it has been set up before having this issue closed?
You can also actually close the issue using the button below, updating with a comment about why/ how this issue has been closed :) 

Thank you

**Comment by aquaomarine** [comment]
Set up [Calendly](calendly.com/bromineresearch/) and Reviewed during Call with Marija Jan 26
