### ISSUE TITLE
Meet about Wild/Crazy8s ideation

### ISSUE THREAD

**Issue by Globnartheexquisite** [saucelabs/elemental-bromine#27]
# Description

We are beginning to develop wireframes for the tip site so that we actually have a form of front end to test. I'd like to meet with the team to discuss their thought process in the crazy8s sketching exercise last week. 

# Criteria

- [x] Meet on zoom, talk about crazy8s
- [ ] Django to synthesize takeaways in their document

**Comment by Roseywinter** [comment]
Checked box "Meet on zoom, talk about crazy8s", as we did meet and discuss the Crazy8s exercise. @Globnartheexquisite did you "synthesize takeaways in their document"?

**Comment by Globnartheexquisite** [comment]
@Roseywinter yep all done, issue closed with this comment.
