### ISSUE TITLE
Create a Vue App

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-bromine#3]
# Description
initialize Vue and create project folder structure

resource: https://vuejs.org/guide/quick-start.html

# Acceptance Criteria 

- [x] Initial Build of Vue App

**Comment by daniellemadry** [comment]
I initiated vue and created the app. I just need the project folder structure

**Comment by daniellemadry** [comment]
I will be pushing the changes once I've set up the folders. should I go ahead and do it before? @discombobulateme

**Comment by discombobulateme** [comment]
@daniellemadry can you please add the PR to be reviewed? :) thank you!

**Comment by daniellemadry** [comment]
Done @discombobulateme
