### ISSUE TITLE
Create February Elemental Bromine update

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-bromine#34]

**Comment by discombobulateme** [comment]
Subscribers to Elemental Selenium should receive monthly updates about the project revamp.
This month:

- [ ] Users interviews
- [ ] Survey results (can we share?)
- [ ] Add a banner to promote the Selenium conference (waiting for a Elemental Selenium promo code)

**Comment by janackeh** [comment]
Here is the February update I created : https://docs.google.com/document/d/1Dlv5IqNpRIp-wR-jTzEBwBB59SX40LiiA7H7wwb8-GY/edit?usp=sharing

**Comment by discombobulateme** [comment]
BEAUTIFUL job! Thank you!

**Comment by janackeh** [comment]
Accepted all of the edits
