### ISSUE TITLE
Create a new subscription confirmation text

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-bromine#37]
When users subscribe to Elemental Selenium they receive the following email signed by Dave: 

![Image](https://user-images.githubusercontent.com/7980624/218723797-cf46f4ec-5b84-4f23-80ed-33df8031328f.png)

There's several issues there, and the subscription text needs to reflect that: 

- [ ] Upper banner should not mention: full copy of The Selenium Guidebook, or attended one of Dave's webinars, instead, add some useful resources users can feel valued, such as: Nikolay's The[ Test Automation Experience](https://www.youtube.com/@test-automation-experience/about) channel or a link to Boni's book [Hands-On Selenium WebDriver](https://www.oreilly.com/library/view/hands-on-selenium-webdriver/9781098109998/) with Java or free article
- [ ] We should not be using Dave's name as a propaganda... please change this phrase and add some other important Selenium reference _Did you know Dave uses Sauce Labs to test his applications? _ . You can ask @diemol for a neutral influence person or project that uses Sauce
- [ ] Change postal address in the bottom to Sauce Labs main headquarter addreee

**Comment by discombobulateme** [comment]
When users subscribe to Elemental Selenium they receive the following email signed by Dave: 



![Image](https://user-images.githubusercontent.com/7980624/218723797-cf46f4ec-5b84-4f23-80ed-33df8031328f.png)

There's several issues there, and the subscription text needs to reflect that: 

- [ ] Upper banner should not mention: full copy of The Selenium Guidebook, or attended one of Dave's webinars, instead, add some useful resources users can feel valued, such as: Nikolay's The[ Test Automation Experience](https://www.youtube.com/@test-automation-experience/about) channel or a link to Boni's book [Hands-On Selenium WebDriver](https://www.oreilly.com/library/view/hands-on-selenium-webdriver/9781098109998/) with Java or free article
- [ ] We should not be using Dave's name as a propaganda... please change this phrase and add some other important Selenium reference _Did you know Dave uses Sauce Labs to test his applications? _ . You can ask @diemol for a neutral influence person or project that uses Sauce
- [ ] Change postal address in the bottom to Sauce Labs main headquarter addreee

**Comment by Roseywinter** [comment]
I created a new subscription confirmation text in Google Docs: https://docs.google.com/document/d/1p3M2oKHzrjVLwoqy5ujKy6uAkBgEg7hBLwjbfx12k8U/edit?usp=sharing

**Comment by Roseywinter** [comment]
@janackeh @aquaomarine @discombobulateme Please review, thank you!

**Comment by janackeh** [comment]
@Roseywinter  
- minor change - can you take out the ! after "visit the Sauce Labs website for more info"?

**Comment by Roseywinter** [comment]
@janackeh Done! - Took out the ! after "visit the Sauce Labs website for more info" as requested.

**Comment by discombobulateme** [comment]
Uhuuu thank you!
