### ISSUE TITLE
Present Elemental Bromine to Sauce Labs Community Team

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-bromine#38]
As we ended our discovery phase, we must provide accountability to our stakeholders who are supporting this project.
The first stakeholders we will provide that is Sauce Labs Community Team.
This presentations should contain the following and should take no longer than 10-15min:

- [ ] What you are proposing to change, based on the discovery phase (content audit, users survey and interviews, group discussion, mentorship discovery)
- [ ] Add data to what you are proposing: why are you proposing that?
- [ ] How are you proposing that? Show what you have: wireframe, image, template, graphic, prototype
- [ ] Have something in place to allow the stakeholder to give their opinion. Will you setup a working group to iterate over a prototype? Ask questions? Which questions?
- [ ] Everyone should present something, considering updates about the working group you are responsible for
- [ ] You can use the Design brief to explain why it needs to be build and how will you do that

Presentation date: February 21st 3pm UTC time, invites already on everyone's calendar.

**For the meeting preparation, some tasks:**

- [ ] Meet some time this week as group to discuss the presentation (what and how)
- [ ] Before the meeting, you should have individual tasks to prepare for the meeting
- [ ] Separate the presentation into sections and main messages, organize it collaboratively

**Comment by Globnartheexquisite** [comment]
My presentation will contain:
Moodboard
Basic wireframes (black & white, generic sans serif, no graphics, no images, etc) 
Projected roadmap for prototyping (wireframes -> tip site -> community pages -> community contributions) 

If people are interested I can walk our team through the basic gist on Friday.

**Comment by discombobulateme** [comment]
Presented beautifully <3
