### ISSUE TITLE
Heuristic Analysis

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-bromine#7]
# Description

Finish performing the first pass of heuristic analysis on the elemental selenium website. 

## Useful Resources
- [Research Brief ](https://docs.google.com/document/d/1pRZfa-_zuG7ufHgwF8RhGUav8JOOPm3ppjooMSzX3cQ/edit?usp=sharing)
- The analysis is being done using a penpot file. To get access, please login and add your email in the comments on this issue

# Acceptance Criteria 

- [x] Django has performed a heuristic analysis and added his findings to the PenPot
- [ ] Janackeh has performed a heuristic analysis and added her findings to the PenPot 
- [x] Esther has performed a heuristic analysis and added her findings to the PenPot
- [ ] Danielle has performed a heuristic analysis and added her findings to the PenPot
- [x] Rajene has performed a heuristic analysis and added her findings to the PenPot 

- [x] Mailing list sign up flow has been audited

- [x] Navigating to tip archive has been audited 

- [ ] Sample of ten randomly selected individual tips have been audited

**Comment by daniellemadry** [comment]
daniellemadry6@gmail.com for access.

**Comment by Globnartheexquisite** [comment]
Heuristic analysis has been completed and approved, any further evaluation of old designs to be taken on by UXRD
