### ISSUE TITLE
Content Audit

### ISSUE THREAD

**Issue by discombobulateme** [saucelabs/elemental-bromine#8]
# Description

Audit all content on the [Elemental Selenium website](http://elementalselenium.com/), including the landing page and [tip archive ](http://elementalselenium.com/tips) table of contents. 

## Relevant Links

Audit spreadsheet: https://docs.google.com/spreadsheets/d/10UpvsSHY0NH48FafkUV8ZKYbYTHlGbAuG8UUpq54rpo/edit#gid=0

# Acceptance Criteria

- [ ] All tips have all relevant fields filled out in the spreadsheet listed above
- [ ] Landing page and tip archive table of contents have also been audited for:
- [ ] Typos
- [ ] Vernacular
- [ ] Linguistic Consistencies 
- [ ] Navigation Consistencies

**Comment by discombobulateme** [comment]
Hi @Globnartheexquisite!
I see this issue in the review. Can you attribute someone to review it, please?

**Comment by Globnartheexquisite** [comment]
@discombobulateme 

Sure thing, just added Janackeh

**Comment by discombobulateme** [comment]
@janackeh can you please review this issue?

**Comment by Globnartheexquisite** [comment]
Content audit completed, final findings visible in the spreadsheet.
